using System;
using System.Linq;
using UnityEngine;
namespace VJPractice.Stage {
public sealed partial class VJStage {
 public int LyricMode;public float Fps{get;private set;}public float P95{get;private set;}int parameter;RemoteDeck remote;
 readonly float[] frameTimes=new float[180];int frameIndex,frameCount;float nextStats;GUIStyle[] cachedLabels=new GUIStyle[65];
 public void ApplyControl(string action,float value){switch(action){case "energy":Energy=Mathf.Clamp01(value);break;case "density":Density=Mathf.Clamp01(value);break;case "flow":Flow=Mathf.Clamp01(value);break;case "echo":Echo=Mathf.Clamp01(value);break;case "visual":SetTemplate(Mathf.Clamp((int)value,0,5));break;case "lyric":LyricMode=Mathf.Clamp((int)value,0,5);break;case "play":TogglePlay();break;case "seek":Seek(value);break;case "freeze":Frozen=!Frozen;break;case "blackout":Blackout=!Blackout;break;case "clean":CleanOutput=!CleanOutput;break;case "offset":Document.offsetSeconds+=Mathf.Clamp(value,-1,1);break;case "spotify":OpenSpotify();break;case "tap":double now=Time.unscaledTimeAsDouble,delta=now-lastTap;if(lastTap>=0&&delta>=.25&&delta<=1.5)Bpm=(float)(60/delta);lastTap=now;beat=0;break;}}
 void PerformanceInit(){var old=templates;templates=new StageTemplate[6];Array.Copy(old,templates,Mathf.Min(old.Length,6));string[] titles={"04 / 隧道 · Tunnel","05 / 矩陣 · Matrix","06 / 流體 · Fluid"};Color[] colors={new Color(.1f,.65f,1),new Color(.18f,.85f,.55f),new Color(.9f,.22f,.45f)};for(int i=3;i<6;i++){var p=ScriptableObject.CreateInstance<StageTemplate>();p.title=titles[i-3];p.primary=colors[i-3];p.accent=i==3?new Color(1,.35f,.12f):i==4?new Color(.7f,.95f,.95f):new Color(.3f,.3f,1);p.visualMode=i;p.energy=.65f;p.density=.6f;p.flow=.45f;p.echo=.6f;templates[i]=p;}remote=gameObject.AddComponent<RemoteDeck>();remote.Begin(this);}
 void PerformanceUpdate(){float ms=Time.unscaledDeltaTime*1000;if(ms>0){frameTimes[frameIndex++%frameTimes.Length]=ms;frameCount=Mathf.Min(frameCount+1,frameTimes.Length);}if(Time.unscaledTime>nextStats&&frameCount>0){nextStats=Time.unscaledTime+1;var copy=frameTimes.Take(frameCount).OrderBy(v=>v).ToArray();Fps=1000/Mathf.Max(1,copy.Average());P95=copy[Mathf.Clamp(Mathf.FloorToInt(copy.Length*.95f),0,copy.Length-1)];}}
 void Nudge(float amount){switch(parameter){case 0:Energy=Mathf.Clamp01(Energy+amount);break;case 1:Density=Mathf.Clamp01(Density+amount);break;case 2:Flow=Mathf.Clamp01(Flow+amount);break;case 3:Echo=Mathf.Clamp01(Echo+amount);break;}}
 void DrawPerformancePage(){Caption(1120,231,"歌詞模式 / Q W E R T Y",15,ink,298);string[] names={"Q 字幕","W 斜切","E 環繞","R 打字","T 字雨","Y 海報"};for(int i=0;i<6;i++)if(Action(1120+(i%2)*153,280+(i/2)*45,145,names[i],LyricMode==i))LyricMode=i;Caption(1120,427,"鍵盤演出",15,ink,298);Caption(1120,465,"1–6：視覺    Q–Y：歌詞\n↑↓：選參數   ←→：微調\nShift 加速 · Space 播放\nV 打拍 · H 輸出 · F 凍結 · B 黑幕",13,muted,298);Caption(1120,562,"iPad / 同 Wi-Fi 控制",15,ink,298);if(Action(1120,603,145,"開啟控制頁"))Application.OpenURL(remote.Url);if(Action(1273,603,145,"複製連線網址")){GUIUtility.systemCopyBuffer=remote.Url;Message="已複製 iPad 控制網址。";}Caption(1120,650,remote.Online?remote.Url:remote.Error,12,cyan,298);Caption(1120,744,$"{Fps:F0} FPS / P95 {P95:F1} ms",13,cyan,298);}
}
}
