using System;
using System.Collections;
using System.Linq;
using UnityEngine;
using UnityEngine.Networking;
namespace VJPractice.Stage {
public sealed partial class VJStage {
 [Serializable] public class SearchResult {public int id;public string trackName,artistName,albumName,syncedLyrics,plainLyrics;public float duration;}
 [Serializable] class SearchResponse {public SearchResult[] items;}
 SearchResult[] results=Array.Empty<SearchResult>();string lastSpotifyTrack="";string query="Humanoid ZUTOMAYO";bool searching;int tab,lastLyric=-1;float manualScrollUntil;Vector2 libraryScroll;
 SpotifyTransport spotify;bool spotifyMode;BrowserTransport transport;bool browserMode;float songDuration=260;
 readonly Color ink=new Color(.90f,.94f,1),muted=new Color(.48f,.58f,.68f),cyan=new Color(.38f,.85f,.95f),amber=new Color(1,.78f,.51f),panel=new Color(.035f,.055f,.08f),line=new Color(.13f,.20f,.26f);
 GUIStyle field,flat,mini;Texture2D flatTex,hoverTex;
 void ConsoleInit(){PerformanceInit();spotify=gameObject.AddComponent<SpotifyTransport>();transport=gameObject.AddComponent<BrowserTransport>();Audio.Scan();Playing=false;Audio.Source.Pause();Message="先在 Spotify 播放 Humanoid，再按連接；或到音源選原創示範。";}
 void ConsoleStyles(){if(flat!=null)return;flatTex=Solid(new Color(.075f,.12f,.17f));hoverTex=Solid(new Color(.12f,.23f,.29f));flat=new GUIStyle{font=jpFont,fontSize=14,alignment=TextAnchor.MiddleCenter,padding=new RectOffset(9,9,4,4)};flat.normal.background=flatTex;flat.normal.textColor=ink;flat.hover.background=hoverTex;flat.hover.textColor=cyan;flat.active.background=hoverTex;flat.active.textColor=cyan;flat.focused=flat.hover;field=new GUIStyle(flat){alignment=TextAnchor.MiddleLeft,fontSize=15};mini=new GUIStyle(label){fontSize=11};button=flat;}
 Texture2D Solid(Color c){var t=new Texture2D(1,1);t.SetPixel(0,0,c.linear);t.Apply();return t;}
 void Caption(float x,float y,string value,int size=12,Color? color=null,float width=290){size=Mathf.Clamp(size,1,64);var s=cachedLabels[size]??(cachedLabels[size]=new GUIStyle(label){fontSize=size,wordWrap=true});s.normal.textColor=color??ink;GUI.Label(new Rect(x,y,width,78),value,s);}
 bool Action(float x,float y,float w,string text,bool selected=false){if(selected)Fill(new Rect(x-1,y-1,w+2,36),cyan);return GUI.Button(new Rect(x,y,w,34),text,flat);}
 float Fader(float y,string name,float value){Caption(22,y,name,11,parameter==Mathf.RoundToInt((y-303)/62)?cyan:muted,160);Caption(184,y,value.ToString("F2"),12,cyan,55);Rect r=new Rect(22,y+29,216,18);Fill(new Rect(r.x,r.y+7,r.width,3),line);Fill(new Rect(r.x,r.y+7,r.width*value,3),cyan);Fill(new Rect(r.x+r.width*value-3,r.y+2,6,13),ink);var e=Event.current;int id=GUIUtility.GetControlID(FocusType.Passive,r);if(e.type==EventType.MouseDown&&r.Contains(e.mousePosition)){GUIUtility.hotControl=id;e.Use();}if(GUIUtility.hotControl==id&&(e.type==EventType.MouseDrag||e.type==EventType.MouseDown)){value=Mathf.Clamp01((e.mousePosition.x-r.x)/r.width);e.Use();}if(e.rawType==EventType.MouseUp&&GUIUtility.hotControl==id)GUIUtility.hotControl=0;return value;}
 void DrawConsole(){ConsoleStyles();Fill(new Rect(0,0,1440,66),panel);Fill(new Rect(0,66,260,834),panel);Fill(new Rect(1100,66,340,834),panel);Fill(new Rect(260,728,840,172),panel);Fill(new Rect(260,66,1,834),line);Fill(new Rect(1099,66,1,834),line);Fill(new Rect(0,65,1440,1),line);
 Caption(22,13,"NIGHTFLIGHT",25,ink,250);Caption(281,22,"AUDIO / TYPE / MOTION",12,muted,330);Caption(790,22,spotifyMode?(spotify.Connected?"SPOTIFY / SYNC":"SPOTIFY / WAITING"):browserMode?(transport.Connected?"PLAYER SYNC / ONLINE":"PLAYER / WAITING"):Audio.External?"EXTERNAL / MANUAL CLOCK":"LOCAL TRANSPORT",12,cyan,300);if(Action(1210,16,208,"乾淨輸出   H"))CleanOutput=true;
 Caption(22,91,"01  /  VISUAL ENGINE",11,muted);string[] names={"1 漂浮","2 斜光","3 回聲","4 隧道","5 矩陣","6 流體"};for(int i=0;i<6;i++){if(Action(22+(i%2)*113,122+(i/2)*47,103,names[i],TemplateIndex==i))SetTemplate(i);}Caption(22,275,"↑↓ 選參數 · ←→ 調整",11,muted);Energy=Fader(303,"ENERGY / 強度",Energy);Density=Fader(365,"DENSITY / 密度",Density);Flow=Fader(427,"FLOW / 流速",Flow);Echo=Fader(489,"ECHO / 殘影",Echo);
 if(Action(22,556,103,"凍結  F",Frozen))Frozen=!Frozen;if(Action(135,556,103,"黑幕  B",Blackout))Blackout=!Blackout;
 Caption(22,616,Audio.External?"SIGNAL / EXTERNAL":"SIGNAL / LOCAL",11,muted);for(int i=0;i<3;i++){float v=Audio.Bands[i];Caption(22,646+i*41,new[]{"LOW","MID","HIGH"}[i],11,muted,60);Fill(new Rect(78,655+i*41,126,5),line);Fill(new Rect(78,655+i*41,126*v,5),cyan);Caption(211,646+i*41,v.ToString("F1"),11,cyan,40);}Caption(22,785,$"{Bpm:F0} BPM   /   V TAP\n{(particles?particles.aliveParticleCount:0):N0} PARTICLES\n{Fps:F0} FPS · P95 {P95:F1} ms",12,muted,216);
 Caption(283,85,templates[TemplateIndex].title,13,new Color(.65f,.8f,.85f),470);Caption(283,695,spotifyMode?spotify.Title+" / "+spotify.Artist:browserMode?"HUMANOID / ZUTOMAYO":Audio.External?"EXTERNAL AUDIO":Audio.Source.clip==Audio.demo?"ORIGINAL DEMO / 原創練習音軌":Audio.Source.clip?.name??"NO AUDIO",11,cyan,780);
 DrawLibrary();DrawTransport();textEditing=GUI.GetNameOfFocusedControl()=="Search"||GUI.GetNameOfFocusedControl()=="ImportPath";
 }
 void DrawLibrary(){Caption(1120,91,"02  /  MUSIC & LYRICS",11,muted);if(Action(1120,122,298,"連接 Spotify · 歌曲時間同步"))OpenSpotify();string[] tabs={"搜尋","歌詞","音源","演出"};for(int i=0;i<4;i++)if(Action(1120+i*76,176,70,tabs[i],tab==i)){tab=i;libraryScroll=Vector2.zero;}
 if(tab==0){GUI.SetNextControlName("Search");query=GUI.TextField(new Rect(1120,228,298,36),query,field);GUI.enabled=!searching;if(Action(1120,278,298,searching?"搜尋中…":"搜尋完整歌詞 / LRCLIB"))StartCoroutine(SearchLyrics());GUI.enabled=true;Caption(1120,325,"依歌曲版本選擇；含逐行時間戳可直接同步。",12,muted,298);libraryScroll=GUI.BeginScrollView(new Rect(1118,379,310,395),libraryScroll,new Rect(0,0,284,results.Length*122));for(int i=0;i<results.Length;i++){var r=results[i];float y=i*122;Caption(8,y,r.trackName,15,ink,273);Caption(8,y+35,$"{r.artistName} · {r.duration:F0}s\n{r.albumName}",11,muted,273);if(Action(8,y+79,270,string.IsNullOrEmpty(r.syncedLyrics)?"載入完整歌詞 · 尚未對時":"載入完整歌詞 · 已有時間戳")){UseResult(r);tab=1;libraryScroll=Vector2.zero;}}GUI.EndScrollView();}
 else if(tab==1){Caption(1120,228,Document.title.Length>30?Document.title.Substring(0,30)+"…":Document.title,17,ink,298);int count=Document.lines.Count(c=>!string.IsNullOrWhiteSpace(c.text));Caption(1120,278,$"{count} 行 / {Document.timing}\n{Document.source}",11,muted,298);libraryScroll=GUI.BeginScrollView(new Rect(1118,340,310,396),libraryScroll,new Rect(0,0,284,Document.lines.Count*65));int active=Document.ActiveAt(Position);if(Event.current.type==EventType.ScrollWheel&&Event.current.mousePosition.x>1100)manualScrollUntil=Time.unscaledTime+6;if(active!=lastLyric&&Time.unscaledTime>manualScrollUntil){libraryScroll.y=Mathf.Max(0,active*65-130);lastLyric=active;}for(int i=0;i<Document.lines.Count;i++){var c=Document.lines[i];float y=i*65;if(i==active)Fill(new Rect(0,y,284,63),new Color(.06f,.16f,.20f));Caption(8,y+4,c.startTime<0?"未對時":LyricDocument.Format(c.startTime),10,i==active?cyan:muted,65);Caption(72,y+3,c.text,13,ink,204);if(GUI.Button(new Rect(0,y,284,63),GUIContent.none,GUIStyle.none)){SelectedLine=i;if(c.startTime>=0)Seek(c.startTime+Document.offsetSeconds);}}GUI.EndScrollView();if(Action(1120,745,142,"儲存對齊"))SaveSession();if(Action(1272,745,146,"載入儲存"))LoadSession();}
 else if(tab==3){DrawPerformancePage();}
 else {Caption(1120,228,Audio.Status,13,cyan,298);if(Action(1120,293,298,"連接 BlackHole / 重新偵測")){Audio.Scan();ConnectBlackHole();}if(Action(1120,339,298,"外部音源 · 手動計時")){browserMode=false;spotifyMode=false;spotify.Enabled=false;Playing=false;Position=0;Audio.Scan();}float y=388;foreach(var p in Audio.Devices.Select((d,i)=>(d,i))){if(Action(1120,y,298,p.d.Name)){browserMode=false;spotifyMode=false;spotify.Enabled=false;Audio.Select(p.i);Playing=false;Position=0;}y+=42;}if(Action(1120,y+12,142,"原創示範")){browserMode=false;spotifyMode=false;spotify.Enabled=false;Audio.Local(Audio.demo);SetDocument(LyricParser.Parse(demoLyrics.text,"OriginalDemo.lrc","Original practice text"));Playing=true;Seek(0);}if(Action(1272,y+12,146,"匯入音樂 / 歌詞"))PickFile();Caption(1120,y+60,"本機檔案路徑",11,muted,298);GUI.SetNextControlName("ImportPath");importPath=GUI.TextField(new Rect(1120,y+88,298,32),importPath,field);if(Action(1120,y+130,298,"載入路徑"))ImportPath(importPath);}
 Caption(1120,803,Message,12,amber,298);
 }
 void DrawTransport(){Fill(new Rect(260,728,840,1),line);Caption(282,744,LyricDocument.Format(Position),26,ink,170);Caption(457,758,"/ "+LyricDocument.Format(Duration),13,muted,160);if(Action(788,747,126,Playing?"暫停 / Space":"播放 / Space"))TogglePlay();if(Action(924,747,152,"回到開頭"))Seek(0);
 Rect track=new Rect(283,802,793,20);Fill(new Rect(track.x,track.y+5,track.width,3),line);Fill(new Rect(track.x,track.y+5,track.width*Mathf.Clamp01(Position/Duration),3),cyan);for(int i=0;i<Document.lines.Count;i++){var c=Document.lines[i];if(c.startTime<0)continue;float x=track.x+track.width*Mathf.Clamp01((c.startTime+Document.offsetSeconds)/Duration);Fill(new Rect(x,track.y+13,2,5),muted);}var e=Event.current;if((e.type==EventType.MouseDown||e.type==EventType.MouseDrag)&&track.Contains(e.mousePosition)){Seek((e.mousePosition.x-track.x)/track.width*Duration);e.Use();}
 if(Action(283,846,104,"提早 −0.1"))Document.offsetSeconds-=.1f;Caption(404,854,$"OFFSET {Document.offsetSeconds:+0.00;-0.00;0.00}s",12,cyan,230);if(Action(617,846,104,"延後 +0.1"))Document.offsetSeconds+=.1f;if(Action(734,846,170,"下一行打點 / Enter"))Stamp();Caption(924,855,"[  /  ]  微調",11,muted,155);
 }
 void ConnectBlackHole(){int i=Array.FindIndex(Audio.Devices,d=>d.Name.IndexOf("BlackHole",StringComparison.OrdinalIgnoreCase)>=0);if(i>=0){Audio.Select(i);Message="已選 BlackHole；系統輸出需為 VJ Monitor + BlackHole。";}else Message="找不到 BlackHole，請確認已安裝並重開 Unity。";}
 public void OpenSpotify(){browserMode=false;spotifyMode=true;Audio.Source.Stop();Audio.Scan();ConnectBlackHole();spotify.Enabled=true;Message="macOS 若詢問，請允許 Unity 控制 Spotify。";lastSpotifyTrack="";}
 public void OpenHumanoid(){spotifyMode=false;spotify.Enabled=false;browserMode=true;Playing=false;Position=0;Audio.Source.Stop();Audio.Scan();ConnectBlackHole();if(transport.Launch()){Application.OpenURL(transport.Url);Message="請在瀏覽器按播放。聲音與播放位置將分別接入。";}else Message="播放器開啟失敗："+transport.Error;if(!searching)StartCoroutine(SearchLyrics(true));}
 public IEnumerator SearchLyrics(bool autoLoad=false){searching=true;Message="正在搜尋完整來源…";string q=query;float expected=spotifyMode&&spotify.Connected?spotify.Duration:260;using(var req=UnityWebRequest.Get("https://lrclib.net/api/search?q="+UnityWebRequest.EscapeURL(q))){req.timeout=20;req.SetRequestHeader("User-Agent","NightflightVJ/0.3");yield return req.SendWebRequest();if(req.result!=UnityWebRequest.Result.Success){Message="搜尋失敗："+req.error;searching=false;yield break;}try{results=JsonUtility.FromJson<SearchResponse>("{\"items\":"+req.downloadHandler.text+"}").items??Array.Empty<SearchResult>();results=results.OrderBy(r=>string.IsNullOrEmpty(r.syncedLyrics)?1:0).ThenBy(r=>Mathf.Abs(r.duration-expected)).ToArray();Message=$"找到 {results.Length} 個版本，載入時保留來源的所有歌詞行。";if(autoLoad){var match=(q=="Humanoid ZUTOMAYO"?results.FirstOrDefault(r=>r.id==3672778):null)??results.FirstOrDefault(r=>!string.IsNullOrEmpty(r.syncedLyrics)&&Mathf.Abs(r.duration-expected)<3);if(match!=null){UseResult(match);tab=1;}}}catch(Exception ex){Message="來源格式錯誤："+ex.Message;}}searching=false;}
 void SyncSpotifyTrack(){if(!spotify.Connected||spotify.TrackId==lastSpotifyTrack||searching)return;lastSpotifyTrack=spotify.TrackId;query=spotify.Title.Contains("ヒューマノイド")&&spotify.Artist.Contains("ZUTOMAYO")?"Humanoid ZUTOMAYO":spotify.Title+" "+spotify.Artist;SetDocument(new LyricDocument{title=spotify.Title,artist=spotify.Artist,source="等待歌詞來源",timing="尚未載入"});StartCoroutine(SearchLyrics(true));}
 void UseResult(SearchResult r){bool timed=!string.IsNullOrWhiteSpace(r.syncedLyrics);string text=timed?r.syncedLyrics:r.plainLyrics;if(string.IsNullOrWhiteSpace(text)){Message="此版本沒有歌詞，請選其他來源。";return;}var doc=LyricParser.Parse(text,timed?"remote.lrc":"remote.txt","LRCLIB / "+r.id);doc.title=r.trackName;doc.artist=r.artistName;doc.sourceUri="https://lrclib.net/api/get/"+r.id;SetDocument(doc);Debug.Log("VJ_SOURCE_LOADED id="+r.id+" cues="+doc.lines.Count+" duration="+r.duration);songDuration=Mathf.Max(1,r.duration);Message=$"完整來源已載入：{doc.lines.Count(c=>!string.IsNullOrWhiteSpace(c.text))} 行。逐字動畫依行時間估算，可用 offset 微調。";}
}
}
